services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=production
        ports:
            - '4000:4000'
        volumes:
            - ./.env.local:/usr/src/app/.env.local
