services:
    postgres:
        image: postgres:17
        container_name: dev-postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: app
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - app-network
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            timeout: 5s
            retries: 5

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dev-backend
        environment:
            - NODE_ENV=production
            - DB_HOST=postgres
        ports:
            - '4000:4000'
        volumes:
            - ./.env.local:/usr/src/app/.env.local
        networks:
            - app-network
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        depends_on:
            - postgres

networks:
    app-network:
        driver: bridge

volumes:
    postgres-data:
