introspection:
    url: http://localhost:4321/graphql
servers:
    - url: https://api.neuland.app/graphql
      description: Neuland API Server
      production: true
info:
    title: Neuland API Documentation
    description:
        Neuland API uses GraphQL to provide a flexible and powerful API for neuland.app and Neuland Next.
        This documentation provides a detailed overview of the API and its capabilities.
    termsOfService: 'https://assets.neuland.app/datenschutzerklaerung-app.pdf'
    contact:
        name: Neuland Ingolstadt e.V.
        email: info@neuland-ingolstadt.de
        url: https://github.com/neuland-ingolstadt/neuland.app-backend
    license:
        name: AGPL-3.0
        url: 'https://www.gnu.org/licenses/agpl-3.0.html'
extensions:
    scalarGraphql: true
spectaql:
    faviconFile: ./documentation/icon.svg
    theme: spectaql
    logoFile: ./documentation/icon.svg
    targetDir: ./documentation/generated
