"""
Room report input type. Used to create a new report about incorrect room data.
"""
input RoomReportInput {
    """
    Room name
    """
    room: String!
    """
    Reason for the report.
    """
    reason: RoomReportCategory!
    """
    description of the report
    """
    description: String
}

"""
Input type for the multi language string.
"""
input MultiLanguageStringInput {
    en: String!
    de: String!
}

"""
Input type for the university sports event.
"""
input UniversitySportsInput {
    """
    Title of the sports event in different languages
    """
    title: MultiLanguageStringInput!
    """
    Description of the sports event in different languages
    """
    description: MultiLanguageStringInput
    """
    Campus where the sports event belongs to. This is not the location of the event itself.
    """
    campus: CampusType!
    """
    Location of the sports event
    """
    location: String!
    """
    Weekday of the sports event
    """
    weekday: WeekdayType!
    """
    Start time of the sports event as Unix timestamp
    """
    startTime: LocalTime!
    """
    End time of the sports event as Unix timestamp
    """
    endTime: LocalTime
    """
    True if the sports event requires registration
    """
    requiresRegistration: Boolean!
    """
    Invitation link for the sports event, e.g. a WhatsApp group
    """
    invitationLink: String
    """
    E-Mail address for registration or contact
    """
    eMail: EmailAddress
    """
    Category of the sports event (e.g. soccer, basketball, etc.)
    """
    sportsCategory: SportsCategoryType!
}

"""
Input type for the announcement.
"""
input AnnouncementInput {
    """
    Platform where the announcement is displayed
    """
    platform: [Platform!]!
    """
    UserKind to target the announcement to specific user groups
    """
    userKind: [UserKind!]!
    """
    Title of the announcement in different languages
    """
    title: MultiLanguageStringInput!
    """
    Description of the announcement in different languages
    """
    description: MultiLanguageStringInput!
    """
    Start date and time when the announcement is displayed
    """
    startDateTime: DateTime!
    """
    End date and time when the announcement is displayed
    """
    endDateTime: DateTime!
    """
    Priority of the announcement, higher are more important
    """
    priority: Int!
    """
    URL to the announcement
    """
    url: String
}
